version: '3'
services:
  dronekit:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: dronekit_container
    image: biwashi/droekit_img
    tty: true
    # カレントディレクトリとコンテナ内のuer/srcをボリューム
    volumes:
      - ./:/home/user/src
      - /dev/:/dev/
      # - ~/../../tmp:/tmp
    ports:
      - "5760:5760"
      - "8080:8080"
    cap_add:
      - SYS_ADMIN
    devices:
      - /dev/fuse
      # - /dev/:/dev/
      - /dev/tty.usbmodem01:/dev/tty.usbmodem01
    privileged: true
    
