version: '3'
services:
  dronekit:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: dronekit_container
    image: biwashi/droekit_img
    tty: true
    # カレントディレクトリとコンテナ内のuer/srcをボリューム
    volumes:
      - ./:/usr/src
      # - ~/../../tmp:/tmp
    ports:
      - "5760:5760"
      - "8080:8080"
    cap_add:
      - SYS_ADMIN
    devices:
      - /dev/fuse
    privileged: true
    
